jobs:
 - template: default.yml@templates
   parameters:
     setup:
       - script: sudo apt-get install libxcb-composite0-dev libx11-dev
         displayName: "Install build dependencies"
         condition: eq(variables['Agent.OS'], 'Linux')
     minrust: 1.44.1
     clippy: -D clippy::all

resources:
  repositories:
    - repository: templates
      type: github
      name: iceiix/azure-pipelines
      ref: c50d2b8335a6b1856aa2fc4f5f41f6684ef8580c
      endpoint: iceiix
