[package]
name = "steven"
version = "0.0.1"
authors = [ "Thinkofdeath <thinkofdeath@spigotmc.org>" ]

[dependencies]
rustc-serialize = "0.3"
glfw = "0.1.0"
byteorder = "0.3.13"
hyper = "0.6.13"
serde = "0.6.0"
serde_json = "0.6.0"
flate2 = "0.2.9"
zip = "0.1.12"
image = "0.3.12"
time = "0.1.32"

[dependencies.steven_gl]
path = "./gl"
version = "0"

[dependencies.steven_openssl]
path = "./openssl"
version = "0"

[target.x86_64-pc-windows-gnu.dependencies]
glfw = { version = "0.1.0", default-features = false }

[target.x86_64-pc-windows-msvc.dependencies]
glfw = { version = "0.1.0", default-features = false }

[target.i686-pc-windows-gnu.dependencies]
glfw = { version = "0.1.0", default-features = false }

