[package]
name = "steven"
version = "0.0.1"
authors = [ "Thinkofdeath <thinkofdeath@spigotmc.org>" ]
build = "build.rs"

[dependencies]
glutin = "0.3.7"
byteorder = "0.3.13"
hyper = "0.6.13"
serde = "0.6.0"
serde_json = "0.6.0"
flate2 = "0.2.9"
zip = "0.1.12"
image = "0.3.12"
time = "0.1.32"
rand = "0.3.11"
rustc-serialize = "0.3"
log = "0.3.2"
cgmath = "0.3.1"

[dependencies.steven_gl]
path = "./gl"
version = "0"

[dependencies.steven_openssl]
path = "./openssl"
version = "0"
